### ISSUE TITLE
Failover when alarm has no latitude or longitude and Google Geocoder is unavailable

### ISSUE THREAD

**Issue by iverasp** [SINTEF-SIT/emht-app#15]
Instead of placing the alarms at 0.000000, 0.000000

**Comment by iverasp** [comment]
Should not be possible to get an alarm without lat and long?

Edge cases discussed so far are locations that are not geocodable with an address such as cabins or on board transportation.

**Comment by tcarlyle** [comment]
I think that we can skip those cases

**Comment by iverasp** [comment]
Implemented in backend
