### ISSUE TITLE
Make sure all alarm types have icons

### ISSUE THREAD

**Issue by iverasp** [SINTEF-SIT/emht-app#20]

**Comment by tcarlyle** [comment]
check the fall type in specific

**Comment by iverasp** [comment]
Currently there exists icons for the following alarm types:
- safety
- phone
- police
- fire

It seems problematic that the alarms types are not predefined (i.e. they can be set to any arbitrary string). Should any other alarm types be covered?

**Comment by tcarlyle** [comment]
They have been loosely (no enums or such) defined as to match the image names representing the alarms if I remember well (double check with Aleks).

Based on the images, it may be missing an alarm of type "elder" and of type "fall"

**Comment by iverasp** [comment]
Added icons for "elder" and "fall". Changed the code from using a switch on predefined strings for the alarm types to if-statements on whether the alarm type string contains certain key-words, i.e

```
if (this.type.contains("fall")) return R.mipmap.ic_fall_alarm;
```

**Comment by tcarlyle** [comment]
ok!
